# templates/ingress.yaml
# This template creates an Ingress resource to expose the Nginx service.
# It is only created if `ingress.enabled` is set to true in values.yaml.
{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "orchestrator-test-chart.fullname" . }}
  labels:
    {{- include "orchestrator-test-chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "orchestrator-test-chart.fullname" $ }}-nginx
                port:
                  number: {{ $.Values.nginx.service.port }}
          {{- end }}
    {{- end }}
{{- end }}