# templates/postgresql-service.yaml
# This template defines a Kubernetes Service for the PostgreSQL
# database. This exposes the PostgreSQL pods within the cluster.
apiVersion: v1
kind: Service
metadata:
  name: {{ include "orchestrator-test-chart.fullname" . }}-postgresql
  labels:
    {{- include "orchestrator-test-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "orchestrator-test-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql